EmployeeHandler/Models/Converter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Diagnostics;
using System.Text;
using System.Globalization;

namespace EmployeeHandler.Models
{
    public class Converter
    {

        public IList<Employee> convertFromCSV(HttpPostedFileBase file)
        {
            StringBuilder sb = new StringBuilder();
            IList<Employee> employees = new List<Employee>();
            using (var reader = new StreamReader(file.InputStream))
            {
                while (!reader.EndOfStream)
                {
                    var line = reader.ReadLine();
                    var values = line.Split(',');
                    sb.Append(line);
                    Employee emp=new Employee(values[0],Convert.ToDateTime(values[1]),
                    Convert.ToBoolean(values[2]),values[3],Convert.ToDecimal(values[4],new CultureInfo("en-US")));
                    employees.Add(emp);
                }
            }
            return employees;
        }
    } 
}

EmployeeHandler/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeHandler.Models
{
    public class Employee
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }  
        public Boolean Married { get; set; }
        public string Phone { get; set; }
        public Decimal Salary { get; set; }

        public Employee(string Name, DateTime DateOfBirth, Boolean Married,
            string Phone, Decimal Salary)
        {
            this.Name = Name; this.DateOfBirth = DateOfBirth; this.Married = Married;
            this.Phone = Phone; this.Salary = Salary;
        }

        public Employee(int EmployeeId, string Name, DateTime DateOfBirth, Boolean Married,
            string Phone, Decimal Salary)
        {
            this.EmployeeId = EmployeeId;
            this.Name = Name; this.DateOfBirth = DateOfBirth; this.Married = Married;
            this.Phone = Phone; this.Salary = Salary;
        }

        public Employee() { }
    }
}

EmployeeHandler/Models/EmployeeContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace EmployeeHandler.Models
{
    public class EmployeeContext: DbContext
    {
        public EmployeeContext()
            : base("employeesList")
        {
        }
        public DbSet<Employee> Employees { get; set; }

    }
}

EmployeeHandler/Models/EmployeeDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EmployeeHandler.Models
{
    public class EmployeeDTO
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        //[DataType(DataType.Date)]
        public string DateOfBirth { get; set; }
        public Boolean Married { get; set; }
        public string Phone { get; set; }
        public string Salary { get; set; }
    }
}

EmployeeHandler/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.Data;
using System.Data.Entity;
using EmployeeHandler.Models;

namespace EmployeeHandler.Controllers
{
    public class EmployeeController : Controller
    {
        private EmployeeContext context=new EmployeeContext();
        private Converter converter = new Converter();
        
        private string fileName;
        
        //
        // GET: /Employee/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FilterEmployees(string column, string term)
        {
            IList<Employee> emps=null;
            if (column.Equals("Name")) { emps=context.Employees.Where(e=>e.Name.Contains(term)).ToList<Employee>(); }
            else if (column.Equals("DateOfBirth")) { emps = context.Employees.AsEnumerable().Where(e => e.DateOfBirth.ToString().Contains(term)).ToList<Employee>(); }
            else if (column.Equals("Married"))
            {
                if (!term.Equals("True", StringComparison.InvariantCultureIgnoreCase) && !term.Equals("False", StringComparison.InvariantCultureIgnoreCase)) emps = null; //if (term!= "True" && term!= "False") emps=null;
                else emps = context.Employees.AsEnumerable().Where(e => e.Married.Equals(Convert.ToBoolean(term))).ToList<Employee>(); }
            else if (column.Equals("Phone")) { emps = context.Employees.Where(e => e.Phone.Contains(term)).ToList<Employee>(); }
            else if (column.Equals("Salary")) { emps = context.Employees.AsEnumerable().Where(e => e.Salary.CompareTo(Convert.ToDecimal(term))>0).ToList<Employee>(); }
            //return context.Employees.Where(e =>e.GetType().GetProperty(column).GetValue().Equals(term)).;
            Debug.WriteLine("22"+emps);
            if (emps == null) return new HttpStatusCodeResult(404, "Bad filter chosen");
            return PartialView("_GetAll", emps);
        }

        public ActionResult SortEmployees(string column)
        {
            IList<Employee> emps = null;
            if (column.Equals("Name")) {emps = context.Employees.AsEnumerable().OrderBy(e => e.Name).ToList<Employee>(); }
            else if (column.Equals("DateOfBirth")) {emps = context.Employees.AsEnumerable().OrderBy(e => e.DateOfBirth).ToList<Employee>(); }
            else if (column.Equals("Married")) {emps = context.Employees.AsEnumerable().OrderBy(e => e.Married).ToList<Employee>(); }
            else if (column.Equals("Phone")) {emps = context.Employees.AsEnumerable().OrderBy(e => e.Phone).ToList<Employee>(); }
            else if (column.Equals("Salary")) {emps = context.Employees.AsEnumerable().OrderBy(e => e.Salary).ToList<Employee>(); }
            else if (column.Equals("NoSorting")) {emps = context.Employees.ToList<Employee>(); }
            //List<Employee> emps = context.Employees.AsEnumerable().OrderBy(e=>e.GetType().GetProperty(column)).ToList<Employee>();
            Debug.WriteLine("33" + emps[0].EmployeeId + "-" + emps[1].EmployeeId + "-" + emps[2].EmployeeId);
            return PartialView("_GetAll", emps);
        }

        public ActionResult GetAll()
        {
            var list = context.Employees.ToList();
            return PartialView("_GetAll", list);
        }

        public IList<Employee> GetEmployees()
        {
            return context.Employees.ToList();
        }

        public void AddEmployee(Employee emp)
        {
            context.Employees.Add(emp);
            context.SaveChanges();
        }

        [HttpPost]
        public ActionResult Upload()
        {
            HttpPostedFileBase fileBase=null;
            try
             {
                fileBase = Request.Files[0];
       
            }
            catch { return Content("No file chosen"); }

            if (fileBase != null && fileBase.ContentLength > 0)
            {
                fileName = fileBase.FileName;
            }

            try
            {
                IList<Employee> emps = converter.convertFromCSV(fileBase);
                foreach (Employee e in emps)
                {
                    AddEmployee(e);
                }
            }
            catch { return Content("Conversion error"); }

            return Content("File " + fileName + " uploaded");
        }
        
        [HttpPost]     
        public ActionResult Edit(EmployeeDTO newEmployee)
        {
            Employee e = context.Employees.Find(newEmployee.EmployeeId);
            e.Name = newEmployee.Name;
            e.DateOfBirth = Convert.ToDateTime(newEmployee.DateOfBirth).Date;
            e.Married = newEmployee.Married;
            e.Phone=newEmployee.Phone;
            e.Salary=Convert.ToDecimal(newEmployee.Salary);
            try
            {
                context.Entry(e).State = EntityState.Modified;
                context.SaveChanges();
                return PartialView("_GetAll", GetEmployees());
            }
            catch (Exception ex) { 
                return Content("There is no such employee");
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Employee e = context.Employees.Find(id);
            try
            {
                context.Employees.Remove(e);
                context.SaveChanges();
                return PartialView("_GetAll", GetEmployees());
            }
            catch (Exception ex)
            {
                return Content("There is no such employee");
            }
        }

    }
}

EmployeeHandler/Views/Employee/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Contact Manager</title>
    <script src="~/Scripts/jquery-1.8.0.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        var deleteRow;
        $(document).ready(function () {
            $("#btnFileUpload").click(function () {
                var files = $("#fileSelect").get(0).files;
                var fileData = new FormData();
                for (var i = 0; i < files.length; i++) {
                    fileData.append("fileSelect", files[i]);
                }
                console.log(files);
                $.ajax({
                    type: "POST",
                    url: "/Employee/Upload",
                    contentType: false, // Not to set any content header
                    processData: false, // Not to process data
                    data: fileData,
                    success: function (result) {
                        var newHtml = '';
                        newHtml = '<div>' + result + '</div>';
                        $("#uploadCSV").html(newHtml);
                    },
                    error: function (error) {
                        console.log(error);
                        $("#uploadCSV").html('<div>' + error.statusText + '</div>');
                    }
                });
            });
        });
</script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <span>Upload CVS file and <br />
         manipulate data</span>
    <br />
    <div>
                       <input type="file" name="fileToUpload" id="fileSelect" value="Choose CVS file"/>
                       <br />
                       <br />
                       <input type="submit" id="btnFileUpload" value="Upload .CVS Employee file" class="btn btn-primary" />
    </div>
    <br />
    <div id="uploadCSV">
    </div>
    <br />
     <div>
        @using (Ajax.BeginForm("GetAll", "Employee", new AjaxOptions
                    {
                        InsertionMode = InsertionMode.Replace,
                        HttpMethod = "GET",
                        OnFailure = "displayFailed",
                        UpdateTargetId = "createTable",
                    }))
                    {
                        <input type="submit" value="Show Employees" class="btn btn-primary" />
                    }
    </div>
    <div id="createTable">
    </div>
    
</body>
</html>

EmployeeHandler/Views/Shared/_GetAll.cshtml
@model IEnumerable<EmployeeHandler.Models.Employee>
<script>
    var deleteRow3;
    var editRow;
    var saveRow;
    var cancelEdit;
    var validateUpdateRow;

    $(document).ready(function () {
        $("#btnFilter").click(function () {
            var filter = $("#term").val();
            var header;
            header = $("#empList").children("option:selected").val();
            $("#btnFilter").parent().parent().find("#createTable").load('@Url.Content("/Employee/FilterEmployees")', { column:header, term:filter },
            function (response, status, xhr) {
                if (status == "error") {
                    $("#btnFilter").parent().parent().find("#uploadCSV").html(xhr.statusText);
                }
                else $("#btnFilter").parent().parent().find("#uploadCSV").html('');
            });
        });
        $("#sortList").change(function () {
            header = $("#sortList").children("option:selected").val();
            $("#btnFilter").parent().parent().find("#createTable").load('@Url.Content("/Employee/SortEmployees")', { column: header});
        });
        editRow = function (i) {
            $('#btnEdit_' + i.toString()).hide();
            $('#btnDelete_' + i.toString()).hide();
            $('#Name_' + i.toString()).hide();
            $('#DOB_' + i.toString()).hide();
            $('#Married_' + i.toString()).hide();
            $('#Phone_' + i.toString()).hide();
            $('#Salary_' + i.toString()).hide();
            $('#btnUpdate_' + i.toString()).show();
            $('#btnCancel_' + i.toString()).show();
            $('#ttxtName_' + i.toString()).show();
            $('#ttxtDOB_' + i.toString()).show();
            $('#ttxtMarried_' + i.toString()).show();
            $('#ttxtPhone_' + i.toString()).show();
            $('#ttxtSalary_' + i.toString()).show();
        }

        cancelEdit = function (i) {
            $('#btnEdit_' + i.toString()).show();
            $('#btnDelete_' + i.toString()).show();
            $('#Name_' + i.toString()).show();
            $('#DOB_' + i.toString()).show();
            $('#Married_' + i.toString()).show();
            $('#Phone_' + i.toString()).show();
            $('#Salary_' + i.toString()).show();
            $('#btnUpdate_' + i.toString()).hide();
            $('#btnCancel_' + i.toString()).hide();
            $('#ttxtName_' + i.toString()).hide();
            $('#ttxtDOB_' + i.toString()).hide();
            $('#ttxtMarried_' + i.toString()).hide();
            $('#ttxtPhone_' + i.toString()).hide();
            $('#ttxtSalary_' + i.toString()).hide();
        }

        saveRow = function (i) {
            if (!validateUpdateRow(i)) return;
            var item = {};
                item["EmployeeId"] = i;
                var newName = $("#txtName_" + i.toString()).val(); item["Name"] = newName;
                var newDOB = $("#txtDOB_" + i.toString()).val(); var parseDate = newDOB.split(".");
                item["DateOfBirth"] = newDOB;
                var newMarried = $("#txtMarried_" + i.toString()).prop('checked');; item["Married"] = Boolean(newMarried);
                var newPhone = $("#txtPhone_" + i.toString()).val(); item["Phone"] = newPhone;
                var newSalary = $("#txtSalary_" + i.toString()).val(); newSalary2 = newSalary.replace(",",".");
                item["Salary"] = newSalary;
                var jsonItem = JSON.stringify(item);
                console.log(item);
                $("#btnFilter").parent().parent().find("#createTable").load('@Url.Content("/Employee/Edit")', item);
        }
            deleteRow=function (n) {
            $("#btnFilter").parent().parent().find("#createTable").load('@Url.Content("/Employee/Delete")', { id: n });
            }

        validateUpdateRow = function (i) {
            var isValid = true;
            var msg = "";

            var Name = $("#txtName_" + i.toString()).val();
            var DOB = $("#txtDOB_" + i.toString()).val();
            var Phone = $("#txtPhone_" + i.toString()).val();
            var Salary = $("#txtSalary_" + i.toString()).val();
    
            if (Name == "") {
                msg += "Name at id:" + i + " is required. " + "\n";
                isValid = false;
            }

            if (DOB == "") {
                msg += "DateOfBirth at id:" + i + " is required. " + "\n";
                isValid = false;
            }

            if (Phone == "") {
                msg += "Phone number at id:" + i + " is required. " + "\n";
                isValid = false;
            }

            if (Salary == "") {
                msg += "Salary field at id:" + i + " is empty. " + "\n";
                isValid = false;
            }
            if (msg!="") alert(msg);
            return isValid;
        }


    });
</script>
<select name="emps" id="empList">
        <option value="Name">Name</option>
        <option value="DateOfBirth">DateOfBirth</option>
        <option value="Married">Married</option>
        <option value="Phone">Phone</option>
        <option value="Salary">Salary</option>
    </select>
    <input type="text" id="term" />
    <input type="submit" id="btnFilter" value="Filter"/>
    <label> Sort by</label>
    <select name="emps" id="sortList">
        <option value="field:">field:</option>
        <option value="Name">Name</option>
        <option value="DateOfBirth">DateOfBirth</option>
        <option value="Married">Married</option>
        <option value="Phone">Phone</option>
        <option value="Salary">Salary</option>
        <option value="NoSorting">No Sorting</option>
    </select>
    <table id="tableEmps">
        <tr id="hRow">
            <th id="hName">
                @Html.DisplayNameFor(model=>model.Name)
            </th>
            <th id="hDOB">
                @Html.DisplayNameFor(model=>model.DateOfBirth)
            </th>
            <th id="hMarried">
                @Html.DisplayNameFor(model=>model.Married)
            </th>
            <th id="hPhone">
                @Html.DisplayNameFor(model=>model.Phone)
            </th>
            <th id="hSalary">
                @Html.DisplayNameFor(model=>model.Salary)
            </th>
        </tr>
        <tbody>
            @if (Model!= null) {
                foreach (var item in Model)  //@foreach
        {  
            <tr id="Tr_@item.EmployeeId.ToString()">
                <td id="Name_@item.EmployeeId.ToString()">
                    @Html.DisplayFor(modelItem=>item.Name)
                </td>
                <td id="DOB_@item.EmployeeId.ToString()">
                    @Html.DisplayFor(modelItem=>item.DateOfBirth)
                </td>
                <td id="Married_@item.EmployeeId.ToString()">
                    @Html.DisplayFor(modelItem=>item.Married)
                </td>
                <td id="Phone_@item.EmployeeId.ToString()">
                    @Html.DisplayFor(modelItem=>item.Phone)
                </td>
                <td id="Salary_@item.EmployeeId.ToString()">
                    @Html.DisplayFor(modelItem=>item.Salary)
                </td>
                <td id="ttxtName_@item.EmployeeId.ToString()" style="display:none;">
                    <input type='text' id="txtName_@item.EmployeeId.ToString()" size="16" value="@item.Name" /></td>
                <td id="ttxtDOB_@item.EmployeeId.ToString()" style="display:none;">
                    <input type='text' id="txtDOB_@item.EmployeeId.ToString()" size="7" value="@item.DateOfBirth.ToString("dd.MM.yyyy")" /></td>
                <td id="ttxtMarried_@item.EmployeeId.ToString()" style="display:none;">
                    <input type='checkbox' id="txtMarried_@item.EmployeeId.ToString()" value="@item.Married" /></td>
                <td id="ttxtPhone_@item.EmployeeId.ToString()" style="display:none;">
                    <input type='text' id="txtPhone_@item.EmployeeId.ToString()" size="9" value="@item.Phone" /></td>
                 <td id="ttxtSalary_@item.EmployeeId.ToString()" style="display:none;">
                     <input type='text' id="txtSalary_@item.EmployeeId.ToString()" size="7" value="@item.Salary" /></td>
                <td>
                     <button type="submit" id="btnEdit_@item.EmployeeId.ToString()" value="Edit" onclick="editRow(@item.EmployeeId)">Edit</button>
                     <button type="submit" id="btnUpdate_@item.EmployeeId.ToString()" class="update" value="Update" style="display:none;" onclick="saveRow(@item.EmployeeId)">Update</button>
                     <button type="submit" id="btnDelete_@item.EmployeeId.ToString()" value="Delete" onclick="deleteRow(@item.EmployeeId)">Delete</button>
                     <button type="submit" id="btnCancel_@item.EmployeeId.ToString()" class="update" value="Cancel" style="display:none;" onclick="cancelEdit(@item.EmployeeId)">Cancel</button>
                </td>
            </tr>
        } }
        </tbody>
  </table>

EmployeeHandler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>